FROM javiermares/tiny-chat
RUN mkdir /iexec
RUN cp my_model_weights.h5 /iexec
RUN cp saved_answer /iexec
RUN cp saved_context /iexec
RUN cp split_qa.py /iexec
RUN cp my_model_weights.h5 /iexec
RUN cp my_model_weights20.h5 /iexec
RUN cp conversation.py /iexec
RUN cp my_model_weights_discriminator.h5 /iexec
RUN cp conversation_discriminator.py /iexec
RUN cp oneturn.py /iexec
RUN cp train_bot.py /iexec
RUN cp get_train_data.py /iexec
RUN cp requirements.txt /iexec
RUN cp vocabulary_movie /iexec
